services:
  moodle:
    build: .
    ports:
      #Add port 80 if you want, or change your server port
      - "8080:8080"
    volumes:
      - moodledata:/var/moodledata
    environment:
      - MOODLE_URL=http://localhost:8000
    depends_on:
      - db

  db:
    image: mysql:5.7
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      #Change your SQL server port if you want
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: yourpassword
      MYSQL_DATABASE: moodle
      MYSQL_USER: moodle
      MYSQL_PASSWORD: yourpassword

volumes:
  moodledata:
  dbdata:
