services:
  moodle:
    build: .
    ports:
      - "8000:8080"
    volumes:
      - moodledata:/var/moodledata
    environment:
      - MOODLE_URL=http://localhost:8000
    depends_on:
      - db

  db:
    image: mysql:5.7
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "8001:3306"
    environment:
      MYSQL_ROOT_PASSWORD: yourpassword
      MYSQL_DATABASE: moodle
      MYSQL_USER: moodle
      MYSQL_PASSWORD: yourpassword

volumes:
  moodledata:
  dbdata:
